-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 09:56:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bedrijfsuitje
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bedrijfsuitje
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bedrijfsuitje` DEFAULT CHARACTER SET utf8 ;
USE `bedrijfsuitje` ;

-- -----------------------------------------------------
-- Table `bedrijfsuitje`.`activiteit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bedrijfsuitje`.`activiteit` ;

CREATE TABLE IF NOT EXISTS `bedrijfsuitje`.`activiteit` (
  `idactiviteit` INT NOT NULL AUTO_INCREMENT,
  `naam` NVARCHAR(80) NOT NULL,
  `omschrijving` NVARCHAR(1200) NOT NULL,
  `locatie` NVARCHAR(100) NOT NULL,
  `begintijd` TIME NOT NULL,
  `eindtijd` TIME NOT NULL,
  `deadline` DATE NOT NULL,
  `aantal` INT NOT NULL,
  PRIMARY KEY (`idactiviteit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bedrijfsuitje`.`personeel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bedrijfsuitje`.`personeel` ;

CREATE TABLE IF NOT EXISTS `bedrijfsuitje`.`personeel` (
  `idpersoneel` INT NOT NULL AUTO_INCREMENT,
  `voorletters` NVARCHAR(25) NOT NULL,
  `tussenvoegsel` NVARCHAR(45) NULL,
  `achternaam` NVARCHAR(45) NOT NULL,
  `email` NVARCHAR(450) NOT NULL,
  `voucher` NVARCHAR(4) NOT NULL,
  PRIMARY KEY (`idpersoneel`,`voucher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bedrijfsuitje`.`inschrijving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bedrijfsuitje`.`inschrijving` ;

CREATE TABLE IF NOT EXISTS `bedrijfsuitje`.`inschrijving` (
  `activiteitid` INT NOT NULL,
  `personeelid` INT NOT NULL,
  PRIMARY KEY (`activiteitid`, `personeelid`),
  CONSTRAINT `activiteit_inschrijving`
    FOREIGN KEY (`activiteitid`)
    REFERENCES `bedrijfsuitje`.`activiteit` (`idactiviteit`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `personeel_inschrijving`
    FOREIGN KEY (`personeelid`)
    REFERENCES `bedrijfsuitje`.`personeel` (`idpersoneel`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bedrijfsuitje`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bedrijfsuitje`.`users` ;

CREATE TABLE IF NOT EXISTS `bedrijfsuitje`.`users` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
